title: Not the Rensselaer Handbook
description: The classic guide for RPI knurds
theme: just-the-docs

url: https://drbarnack.github.io/ntrh

aux_links:
  RPI: https://www.rpi.edu
  Repository: https://github.com/DrBarnack/ntrh
